# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/yoshi/Code/personal/gzdoom/build-ios.vulkan/CMakeFiles/CheckTypeSize/OFF64_T.c))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/yoshi/Code/personal/gzdoom/libraries/zlib/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/CheckFunctionExists.c))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/CheckFunctionExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/CheckIncludeFileCXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/CheckTypeSize.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.21.3/share/cmake/Modules/CheckTypeSize.cmake))

/Users/yoshi/Code/personal/gzdoom/build-ios.vulkan/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.21.3/bin/cmake -H/Users/yoshi/Code/personal/gzdoom -B/Users/yoshi/Code/personal/gzdoom/build-ios.vulkan
